apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: thumbsBinding
spec:
  type: bindings.azure.blobstorage
  version: v1
  metadata:
  - name: storageAccount
    secretKeyRef:
      name: cxns:storage
      key: cxns:storage
  - name: storageAccessKey
    secretKeyRef:
      name: keys:storage
      key: keys:storage
  - name: container
    value: thumbs
  - name: decodeBase64
    value: false
  - name: getBlobRetryCount
    value: 5

auth:
  secretStore: secretStore